### PR TITLE
2.0 Fix setuptools and PyInstaller (#435)

### PR DESCRIPTION
**Pull request by janisz**
https://github.com/pypa/setuptools/issues/1963#issuecomment-607078946
Fixes: D2IQ-67106
Backports:  #435 #430

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run all integration tests

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Review by DominikDary — APPROVED** [review]

**Pull request merged**
