### PR TITLE
[2.0] Backport ssh fixes

### PR DESCRIPTION
**Pull request by janisz**
Backports #https://github.com/dcos/dcos-core-cli/pull/448

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Review by pierrebeitz — APPROVED** [review]

**Pull request merged**
