### PR TITLE
Updated test_killing_app().

### PR DESCRIPTION
**Pull request by armandgrillet**

### CODE REVIEW

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run windows integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run linux integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Pull request closed without merging**
