### PR TITLE
Removed references to `DCOS_PACKAGE_METADATA` from tests.

### PR DESCRIPTION
**Pull request by armandgrillet**
Due to https://github.com/dcos/cosmos/commit/5dd2b541f5694a65b1943ceb79fd22bfdd2ee1a7, we need to fix our CI.

### CODE REVIEW

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Review by bamarni — APPROVED** [review]

**Comment by armandgrillet** [comment]
Linux and macOS integration tests are passing, gonna push 1 commit to fix the Windows CI and only run that before merging.

**Comment by armandgrillet** [comment]
@mesosphere-ci run windows integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run windows integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run windows integration tests

**Pull request merged**
