### PR TITLE
1.11 backports

### PR DESCRIPTION
**Pull request by bamarni**

### CODE REVIEW

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run windows integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run windows integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run windows integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run windows integration tests

**Comment by armandgrillet** [comment]
` Error: Post http://34.213.236.191/package/describe: context deadline exceeded` on Windows, seems like an issue we've seen last week and fixed.

**Comment by bamarni** [comment]
@mesosphere-ci run windows integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run windows integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Pull request merged**
