### PR TITLE
Add SYSLOG_IDENTIFIER[_PID] to logging output

### PR DESCRIPTION
**Pull request by rgo3**
https://jira.mesosphere.com/browse/DCOS_OSS-4855

### CODE REVIEW

**Review by armandgrillet — APPROVED** [review]

**Comment by rgo3** [comment]
@mesosphere-ci run all integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run all integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run linux integration tests

**Pull request merged**
