### PR TITLE
Fix help output to match UX styleguide

### PR DESCRIPTION
**Pull request by rgo3**
https://jira.mesosphere.com/browse/DCOS_OSS-5110

### CODE REVIEW

**Comment by armandgrillet** [comment]
Shall we run the integration tests as some of them test the help output?

**Review by bamarni — APPROVED** [review]

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Review by armandgrillet — CHANGES_REQUESTED** [review]
I think you have to update `python/lib/dcoscli/dcoscli/data/help/task.txt` in order for the CI to pass.

**Comment by rgo3** [comment]
@ArmandGrillet I thought so too but `task.txt` still shows the `python` help menu and the test for `dcos task --help` are disabled at the moment. I can update the file and enable the test if you like.

**Comment by rgo3** [comment]
@mesosphere-ci run linux integration tests

**Review by armandgrillet — APPROVED** [review]

**Review by bamarni — APPROVED** [review]

**Pull request merged**
