### PR TITLE
1.13 Fix setuptools and PyInstaller (#435)

### PR DESCRIPTION
**Pull request by janisz**
https://github.com/pypa/setuptools/issues/1963#issuecomment-607078946
Fixes: D2IQ-67106
Backports:  #435 #430

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run all integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
Need to rerun test due to github issues https://www.githubstatus.com/incidents/2y6v4ltq26g7

**Review by DominikDary — APPROVED** [review]

**Comment by janisz** [comment]
@mesosphere-ci run all integration tests

**Pull request merged**
