### PR TITLE
[2.1] Simplify the calico wrapper

### PR DESCRIPTION
**Pull request by janisz**
* Do not download CA cert – use the one provided by dcos-cli
* Check https for enterprise – this will test if cert is loaded
* Remove unused calico client
* Check if port is open and skip adminrouter

Fixes: https://jira.d2iq.com/browse/COPS-6353
Bacports:  (#489)

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
CI failed due to a problem with AWS https://mesosphere.slack.com/archives/C5U03P5T6/p1598022560005700?thread_ts=1597928400.001000&cid=C5U03P5T6

**Review by pierrebeitz — APPROVED** [review]

**Pull request merged**
