### PR TITLE
Enable task Go subcommand in dcos-core-cli

### PR DESCRIPTION
**Pull request by bamarni**
https://jira.mesosphere.com/browse/DCOS_OSS-5248

### CODE REVIEW

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run linux integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run linux integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci they'd better be passing

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Pull request merged**
