### PR TITLE
Use the testing/2.0 DC/OS installer

### PR DESCRIPTION
**Pull request by bamarni**
We currently use testing/master, which should only be used in the 2.1-patch.x branch.

### CODE REVIEW

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
The windows test failure is tracked in https://jira.mesosphere.com/browse/DCOS_OSS-5599

**Comment by bamarni** [comment]
@mesosphere-ci run windows integration tests

**Review by janisz — APPROVED** [review]

**Review by drewvanstone — APPROVED** [review]

**Pull request merged**
