### PR TITLE
Update dcos node diagnostic deprecation message

### PR DESCRIPTION
**Pull request by janisz**
Backports:  #452
Fixes: COPS-6209

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-ci run Windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Review by pierrebeitz — APPROVED** [review]

**Pull request merged**
