### PR TITLE
[2.0] Display version for packages with the same name

### PR DESCRIPTION
**Pull request by janisz**
* Display version for pacakges with same name
* Add tests for cosmos client
* Show version for every pacakge instance
* Remove trailing spaces from package list test
* Sort listed packages by name and version
* Merge apps for the same package version

Fixes: https://jira.d2iq.com/browse/D2IQ-70580
Backports:  #484

### CODE REVIEW

**Comment by janisz** [comment]
I think our Windows and Mac tests interfere with dcos-cli builds :(

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Review by pierrebeitz — APPROVED** [review]

**Pull request merged**
