### PR TITLE
Added '--app-id' flag in 'dcos package describe'.

### PR DESCRIPTION
**Pull request by armandgrillet**
This helps to render a specific ID of an app, e.g. when an app has multiple instances running.

### CODE REVIEW

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Review by rgo3 — APPROVED** [review]

**Pull request merged**
