### PR TITLE
Updated download URL for the go wrapper CLI.

### PR DESCRIPTION
**Pull request by rgo3**

### CODE REVIEW

**Comment by rgo3** [comment]
@mesosphere-ci run linux mac integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run linux integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run all integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run all integration tests

**Review by bamarni — APPROVED** [review]

**Comment by bamarni** [comment]
This in combination with your other PR should fix CI in https://github.com/dcos/dcos-core-cli/pull/83

**Pull request merged**
