### PR TITLE
Updated task attach/exec exit strategy.

### PR DESCRIPTION
**Pull request by klueska**

### CODE REVIEW

**Review by armandgrillet — APPROVED** [review]

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Pull request merged**
