### PR TITLE
[1.11] Added region for masters in standby.

### PR DESCRIPTION
**Pull request by armandgrillet**

### CODE REVIEW

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run Mac integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run Mac integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run mac integration tests

**Review by bamarni — APPROVED** [review]

**Pull request merged**
