### PR TITLE
Improved error message for 'task attach' for tasks without a TTY.

### PR DESCRIPTION
**Pull request by klueska**

### CODE REVIEW

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by ArmandGrillet** [comment]
This is not flaky, the three failed Windows runs are consistent:

```
================================== FAILURES ===================================
_____________________________ test_log_completed ______________________________

    def test_log_completed():
        """ Test `dcos task log --completed` """
        # create a completed task
        # ensure that tail lists nothing
        # ensure that tail --completed lists a completed task
        returncode, stdout, stderr = exec_command(
            ['dcos', 'task', 'log', 'test-app-completed'])
    
        assert returncode == 1
        assert stdout == b''
        assert stderr.startswith(b'No running tasks match ID [test-app-completed]')
    
        returncode, stdout, stderr = exec_command(
            ['dcos', 'task', 'log', '--completed', 'test-app-completed', 'stderr'])
>       assert returncode == 0
E       assert 1 == 0

tests\integrations\test_task.py:192: AssertionError
---------------------------- Captured stdout call -----------------------------
CMD: ['dcos', 'task', 'log', 'test-app-completed']
STDOUT: 
STDERR: No running tasks match ID [test-app-completed]; however, there are 2 matching completed tasks. Run with --completed to see these logs.

CMD: ['dcos', 'task', 'log', '--completed', 'test-app-completed', 'stderr']
STDOUT: 
STDERR: found more than one task with the same name: ['test-app-completed.caac70c1-c4ea-11e8-8673-e67d08a4a746', 'test-app-completed.cda82492-c4ea-11e8-8673-e67d08a4a746']. Please provide a unique task name.
```

**Comment by klueska** [comment]
I only changed code in task attach, which doesn’t run on Windows. Do you see how my changes would have affected this failure?

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run all integration tests

**Review by armandgrillet — APPROVED** [review]

**Pull request merged**
