### PR TITLE
Added bad gateway (HTTP 502) handling.

### PR DESCRIPTION
**Pull request by armandgrillet**

### CODE REVIEW

**Comment by armandgrillet** [comment]
@mesosphere-ci run linux integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run windows integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run mac integration tests

**Comment by armandgrillet** [comment]
@bamarni CI failing on macOS due to known CI issue.

**Comment by armandgrillet** [comment]
```
(dcos-cli/cli) ➜  dcoscli (DCOS-22112) ✔ /Users/Armand/Code/dcos-core-cli/python/lib/dcoscli/.tox/py35-unit/bin/py.test -p no:cacheprovider -vv /Users/Armand/Code/dcos-core-cli/python/lib/dcoscli/tests/unit/test_node.py
=============================================================================================== test session starts ===============================================================================================
platform darwin -- Python 3.5.3, pytest-3.9.3, py-1.8.0, pluggy-0.9.0 -- /Users/Armand/Code/dcos-core-cli/python/lib/dcoscli/.tox/py35-unit/bin/python3.5
rootdir: /Users/Armand/Code/dcos-core-cli/python/lib/dcoscli, inifile:
plugins: teamcity-messages-1.21, cov-2.6.1
collected 18 items

tests/unit/test_node.py::test_check_version_fail PASSED                                                                                                                                                     [  5%]
tests/unit/test_node.py::test_check_version_success PASSED                                                                                                                                                  [ 11%]
tests/unit/test_node.py::test_node_diagnostics_create PASSED                                                                                                                                                [ 16%]
tests/unit/test_node.py::test_node_diagnostics_delete PASSED                                                                                                                                                [ 22%]
tests/unit/test_node.py::test_node_diagnostics_list PASSED                                                                                                                                                  [ 27%]
tests/unit/test_node.py::test_node_diagnostics_status PASSED                                                                                                                                                [ 33%]
tests/unit/test_node.py::test_node_diagnostics_cancel PASSED                                                                                                                                                [ 38%]
tests/unit/test_node.py::test_node_diagnostics_download PASSED                                                                                                                                              [ 44%]
tests/unit/test_node.py::test_dcos_log_v2_leader_mesos PASSED                                                                                                                                               [ 50%]
tests/unit/test_node.py::test_dcos_log_v2_leader_marathon PASSED                                                                                                                                            [ 55%]
tests/unit/test_node.py::test_dcos_log_v2_sse PASSED                                                                                                                                                        [ 61%]
tests/unit/test_node.py::test_dcos_log_v2_filters PASSED                                                                                                                                                    [ 66%]
tests/unit/test_node.py::test_dcos_log_leader_mesos PASSED                                                                                                                                                  [ 72%]
tests/unit/test_node.py::test_dcos_log_leader_marathon PASSED                                                                                                                                               [ 77%]
tests/unit/test_node.py::test_dcos_log_stream PASSED                                                                                                                                                        [ 83%]
tests/unit/test_node.py::test_dcos_log_filters PASSED                                                                                                                                                       [ 88%]
tests/unit/test_node.py::test_list_components PASSED                                                                                                                                                        [ 94%]
tests/unit/test_node.py::test_list_components_leader PASSED                                                                                                                                                 [100%]

============================================================================================ 18 passed in 0.73 seconds ============================================================================================
```

**Comment by armandgrillet** [comment]
@mesosphere-ci run mac integration tests

**Review by rgo3 — APPROVED** [review]

**Pull request merged**
