### PR TITLE
Escape remote command when passing it to intermediate ssh call

### PR DESCRIPTION
**Pull request by rgo3**
https://jira.mesosphere.com/browse/DCOS-42048

### CODE REVIEW

**Comment by rgo3** [comment]
@mesosphere-ci run linux integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run mac integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run linux integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run linux integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run linux integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run mac integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run linux integration tests

**Comment by armandgrillet** [comment]
Tested on another branch, this passes if we eliminate the CI issues reported in https://jira.mesosphere.com/browse/DCOS_OSS-4948

**Pull request merged**
