### PR TITLE
Updated all references to 'state.json' to just 'state'.

### PR DESCRIPTION
**Pull request by klueska**
Mesos has now removed the '/state.json' endpoint in favor of '/state'.

### CODE REVIEW

**Comment by bamarni** [comment]
Does it need a backport or is it only since 1.12?

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by klueska** [comment]
Should only be 1.12. It's been deprectated for a long time, but only now finally removed.

**Comment by bamarni** [comment]
Thanks @klueska, I've created https://jira.mesosphere.com/browse/DCOS-41713 for the windows failure, seems to be flaky.

**Pull request merged**
