### PR TITLE
Updated help menu to follow UX guidelines.

### PR DESCRIPTION
**Pull request by rgo3**

### CODE REVIEW

**Comment by rgo3** [comment]
@mesosphere-ci run all integration tests

**Review by bamarni — APPROVED** [review]
LGTM after CI

**Comment by rgo3** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run windows integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run linux integration tests

**Pull request merged**
