### PR TITLE
[1.11] Added '--user' flag to 'dcos service log'.

### PR DESCRIPTION
**Pull request by armandgrillet**

### CODE REVIEW

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci mac integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run Linux integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run mac integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run mac integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run Linux integration tests

**Review by rgo3 — APPROVED** [review]

**Pull request merged**
