### PR TITLE
Update dependecies

### PR DESCRIPTION
**Pull request by janisz**
Update dependencies to latest versions

* https://github.com/dcos/dcos-test-utils/compare/e8519d9c20c4f0859d90a0a1d7eeae5c3c52fe5d...9a9cafdd509bc9b8c76ab5e9f59849e7f3ace765
* https://github.com/dcos/dcos-e2e/compare/2019.04.02.1...2019.10.11.0
* Removed dcos-launch

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Review by makkes — APPROVED** [review]

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by drewvanstone** [comment]
@janisz does this PR make https://github.com/dcos/dcos-core-cli/pull/379 obsolete?

**Comment by janisz** [comment]
@drewvanstone it depends on windows tests

**Pull request closed without merging**
