### PR TITLE
Remove custom escape proxy

### PR DESCRIPTION
**Pull request by bamarni**
There used to be a bug in the Moby terminal escape proxy:

https://github.com/moby/moby/pull/39728

Since it is now fixed upstream, we can remove the patched version from
the codebase.

Additionally, this narrows down the Moby dependency to moby/term
instead of the broad moby/moby package.

### CODE REVIEW

**Comment by janisz** [comment]
We need to wait until we fix our CI

**Review by janisz — APPROVED** [review]

**Review by drewvanstone — APPROVED** [review]

**Review by armandgrillet — APPROVED** [review]

**Comment by janisz** [comment]
@mesosphere-ci run all integration tests

**Comment by janisz** [comment]
@mesosphere-ci run all integration tests

**Comment by janisz** [comment]
@mesosphere-ci run all integration tests

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Comment by janisz** [comment]
@bamarni thanks!

**Pull request merged**
