### PR TITLE
Bumped 'supported_version' to 1.13.

### PR DESCRIPTION
**Pull request by klueska**

### CODE REVIEW

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
The GitHub <=> Jenkins hooks seem down today, probably due to the migration that happened today.

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
Comparing how 1.12 support was added in universe (https://github.com/mesosphere/universe/commit/93437af19652257500ba73d4e3bdf471ff435e91#diff-bb823963d984bdfcf8bfdaee0b95e2a8) with 1.13 (https://github.com/mesosphere/universe/commit/bd10c252b3b2774650c8134a9602158790be68f1#diff-c4ca3bb11e5c023a1b98e58d2c58dcf6), it seems like it's missing some changes in nginx configs.

I've opened https://github.com/mesosphere/universe/pull/2045 and bumped the image tag again in this PR.

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Review by armandgrillet — APPROVED** [review]

**Pull request merged**
