### PR TITLE
Moved CI from us-west-2 to us-east-1.

### PR DESCRIPTION
**Pull request by armandgrillet**

### CODE REVIEW

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run windows integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run windows integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run windows integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run mac integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run linux integration tests

**Comment by janisz** [comment]
Why?

**Pull request merged**
