### PR TITLE
[1.12] Updated 'requests' dependency to 2.20.0.

### PR DESCRIPTION
**Pull request by armandgrillet**

### CODE REVIEW

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@ArmandGrillet : as the private package registry was added in 1.12 too integration tests started to fail. Could you cherry-pick https://github.com/dcos/dcos-core-cli/commit/24a8f3c5a0e65e20064fb2bf1bc190db34dbd94f? Then they should pass in this PR.

**Comment by rgo3** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Review by rgo3 — APPROVED** [review]

**Pull request merged**
