### PR TITLE
Use timeout from dcos config for diagnostic download (#512)

### PR DESCRIPTION
**Pull request by janisz**
* Use timeout from dcos config for diagnostic download

Fixes: https://jira.d2iq.com/browse/COPS-6584

* Check stderr before exit code

It's easier to debug failing test when we have stderr

Backports:  (#512)

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Review by pierrebeitz — APPROVED** [review]

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
@mesosphere-ci run mac integration tests

**Comment by janisz** [comment]
Nobody merged it over a week so I think it's fair to close

**Pull request closed without merging**
