### PR TITLE
Updated urllib3 dependency.

### PR DESCRIPTION
**Pull request by armandgrillet**

### CODE REVIEW

**Comment by armandgrillet** [comment]
@mesosphere-ci run linux integration tests

**Review by bamarni — APPROVED** [review]

**Comment by bamarni** [comment]
LGTM though CI failed

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run linux integration tests

**Pull request merged**
