### PR TITLE
 Improve error messages on 401 and 403 HTTP errors

### PR DESCRIPTION
**Pull request by bamarni**
It used to print `Error: HTTP 401 error`, which is a regression from the
Python CLI.

This adds more informative messages for the common 401 and 403 errors:

- Error: authentication failed, please run `dcos auth login`
- Error: you are not authorized to perform this operation

https://jira.mesosphere.com/browse/DCOS_OSS-5117

### CODE REVIEW

**Review by rgo3 — APPROVED** [review]

**Comment by armandgrillet** [comment]
```
# github.com/dcos/dcos-core-cli/pkg/metronome
pkg\metronome\client.go:411:4: cannot use promoted field Response in struct literal of type httpclient.HTTPError
# github.com/dcos/dcos-core-cli/pkg/metronome [github.com/dcos/dcos-core-cli/pkg/metronome.test]
pkg\metronome\client.go:411:4: cannot use promoted field Response in struct literal of type httpclient.HTTPError
mingw32-make: *** [Makefile:39: vet] Error 2
```
What is that?

**Comment by bamarni** [comment]
I have to make a patch to the dcos-cli to make a propery exported, see the `Temporary patch to dcos-cli` commit. I think our build system doesn't use the vendor folder but downloads the references in go.mod / go.sum.

**Comment by bamarni** [comment]
This is still WIP, just wanted to get early feedback

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Review by armandgrillet — APPROVED** [review]

**Pull request merged**
