### PR TITLE
Upgrade to Python 3.7 on UNIX

### PR DESCRIPTION
**Pull request by bamarni**
- [x] linux
- [x] macos
- [x] windows

### CODE REVIEW

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run windows integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Review by armandgrillet — APPROVED** [review]

**Comment by bamarni** [comment]
@mesosphere-ci run windows integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run windows integration tests

**Pull request merged**
