### PR TITLE
Add JSON output to job run command

### PR DESCRIPTION
**Pull request by janisz**
Add missing --json flag to job run command.
This function was in Python code but was missing in Go.

Fixes: D2IQ-68975

### CODE REVIEW

**Comment by pierrebeitz** [comment]
how hard would it be to add a test for that?

**Comment by janisz** [comment]
Hmm, adding integration test should be quite easy. I'll do that. Maybe the test existed before.

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Review by pierrebeitz — APPROVED** [review]
LGTM!

**Pull request merged**
