### PR TITLE
Use 2.1 release for CI

### PR DESCRIPTION
**Pull request by janisz**

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Comment by janisz** [comment]
@mesosphere-ci run windows integration tests

**Review by pierrebeitz — APPROVED** [review]

**Comment by pierrebeitz** [comment]
@mesosphere-ci run windows integration tests

**Comment by pierrebeitz** [comment]
<details>
<summary>Failure</summary>

```
================================== FAILURES ===================================
___________________________ test_list_empty[--json] ___________________________

args = '--json'

    @pytest.mark.parametrize("args", [
        '--json',
        'xyzzy --json',
        '--app-id=/xyzzy --json',
        '--json ceci-nest-pas-une-package',
        '--json --app-id=/' + 'ceci-nest-pas-une-package',
    ])
    def test_list_empty(args):
>       _list(args=args.split(' '), stdout=b'[]\n')

tests\integrations\test_package.py:529: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests\integrations\test_package.py:879: in _list
    assert_command(['dcos', 'package', 'list'] + args, stdout=stdout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmd = ['dcos', 'package', 'list', '--json'], returncode = 0, stdout = b'[]\n'
stderr = b'', env = None, stdin = None

    def assert_command(
            cmd,
            returncode=0,
            stdout=b'',
            stderr=b'',
            env=None,
            stdin=None):
        """Execute CLI command and assert expected behavior.
    
        :param cmd: Program and arguments
        :type cmd: list of str
        :param returncode: Expected return code
        :type returncode: int
        :param stdout: Expected stdout
        :type stdout: bytes
        :param stderr: Expected stderr
        :type stderr: bytes
        :param env: Environment variables
        :type env: dict of str to str
        :param stdin: File to use for stdin
        :type stdin: file
        :rtype: None
        """
    
        returncode_, stdout_, stderr_ = exec_command(cmd, env, stdin)
    
        assert stderr_ == stderr, (stderr_, stderr)
>       assert stdout_ == stdout, (stdout_, stdout)
E       AssertionError: (b'[\n    {\n        "apps": [\n            "/dcos-enterprise-cli"\n        ],\n        "command": {\n            "name": "dcos-enterprise-cli"\n        },\n        "description": "Enterprise DC/OS CLI",\n        "framework": false,\n        "maintainer": "support@mesosphere.io",\n        "marathon": {},\n        "name": "dcos-enterprise-cli",\n        "packagingVersion": "3.0",\n        "releaseVersion": 1301,\n        "selected": true,\n        "tags": [\n            "mesosphere",\n            "enterprise",\n            "subcommand"\n        ],\n        "version": "1.13-patch.1"\n    }\n]\n', b'[]\n')

dcoscli\test\common.py:100: AssertionError
---------------------------- Captured stdout call -----------------------------
CMD: ['dcos', 'package', 'list', '--json']
STDOUT: [
    {
        "apps": [
            "/dcos-enterprise-cli"
        ],
        "command": {
            "name": "dcos-enterprise-cli"
        },
        "description": "Enterprise DC/OS CLI",
        "framework": false,
        "maintainer": "support@mesosphere.io",
        "marathon": {},
        "name": "dcos-enterprise-cli",
        "packagingVersion": "3.0",
        "releaseVersion": 1301,
        "selected": true,
        "tags": [
            "mesosphere",
            "enterprise",
            "subcommand"
        ],
        "version": "1.13-patch.1"
    }
]

STDERR: 
- generated xml file: C:\Users\jenkins\workspace\public-dcos-cluster-ops\mesosphere-dcos-cli\core\integration-tests-windows\python\lib\dcoscli\tests.xml -
============================ slowest 10 durations =============================
102.06s call     tests/integrations/test_marathon.py::test_watching_deployment
48.46s setup    tests/integrations/test_package.py::test_repo_list
44.29s call     tests/integrations/test_marathon_pod.py::test_pod_list
32.31s call     tests/integrations/test_marathon.py::test_leader_delete
32.18s call     tests/integrations/test_marathon_groups.py::test_scale_group
27.97s call     tests/integrations/test_marathon_pod.py::test_pod_update_from_stdin
26.06s call     tests/integrations/test_marathon_groups.py::test_update_group_from_stdin
23.42s call     tests/integrations/test_marathon_groups.py::test_scale_group_when_scale_factor_negative
23.36s call     tests/integrations/test_marathon.py::test_killing_scaling_app
23.29s call     tests/integrations/test_marathon_groups.py::test_group_list_table
=========================== short test summary info ===========================
FAILED tests/integrations/test_package.py::test_list_empty[--json] - Assertio...
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!
```

</details>

**Pull request merged**
