### PR TITLE
Add role columns

### PR DESCRIPTION
**Pull request by ANeumann82**
Add ROLE column to apps, pods and tasks list
Add ENFORCE_ROLE column to group list

JIRA issues: 
DCOS_OSS-5380

### CODE REVIEW

**Comment by armandgrillet** [comment]
@mesosphere-ci run linux integration tests

**Comment by ANeumann82** [comment]
@ArmandGrillet Do you have any idea why the ITs fail? It doesn't really seem related to this PR, but the ITs are failing for a while now...

**Comment by armandgrillet** [comment]
Yes it's https://jira.mesosphere.com/browse/DCOS-57734

**Comment by armandgrillet** [comment]
The CI is fixed 🎉.

**Comment by armandgrillet** [comment]
@mesosphere-ci run linux integration tests

**Comment by armandgrillet** [comment]
`tests/integrations/test_marathon_pod.py::test_pod_list FAILED`
This test needs to be updated.

**Comment by ANeumann82** [comment]
@mesosphere-ci run linux integration tests

**Comment by ANeumann82** [comment]
@mesosphere-ci run linux integration tests

**Review by armandgrillet — APPROVED** [review]

**Comment by ANeumann82** [comment]
@ArmandGrillet Who is landing this PR? I don't have write access to the repo.

**Pull request merged**
