### PR TITLE
[master] Add end of options convention to `dcos task exec`

### PR DESCRIPTION
**Pull request by rgo3**
https://jira.mesosphere.com/browse/DCOS-49325

### CODE REVIEW

**Comment by rgo3** [comment]
@mesosphere-ci run linux integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run mac integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run linux integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run linux integration tests

**Review by armandgrillet — APPROVED** [review]

**Pull request merged**
