### PR TITLE
adding pods to the possible filters for deployments

### PR DESCRIPTION
**Pull request by kensipe**
related to: https://jira.mesosphere.com/browse/DCOS-22632

### CODE REVIEW

**Comment by bamarni** [comment]
@kensipe : there is a lint error : `dcos/marathon.py:487:1: W293 blank line contains whitespace`

Also if we were to run integration tests they would fail at the moment (see https://jira.mesosphere.com/browse/MARATHON-8360), @timcharper fixed it so hopefully it will land in dc/os master soon.

**Comment by bamarni** [comment]
@mesosphere-ci run linux integration tests

**Comment by kensipe** [comment]
@bamarni I bumped marathon on master on a PR today... hoping to be on a train tonight... we will see.

**Comment by kensipe** [comment]
@mesosphere-ci run linux integration tests

**Comment by kensipe** [comment]
@bamarni i get the following when trying to run unit tests... thoughts?

`ERROR: file not found: testspy35-unit`
is there something missing from the repo?  or ?

**Comment by bamarni** [comment]
@mesosphere-ci run all integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run windows integration tests

**Pull request merged**
