### PR TITLE
Add end of options convention to `dcos node ssh` and `dcos task exec`

### PR DESCRIPTION
**Pull request by rgo3**
https://jira.mesosphere.com/browse/DCOS-49325

### CODE REVIEW

**Comment by rgo3** [comment]
@mesosphere-ci run all integration tests

**Review by armandgrillet — APPROVED** [review]

**Comment by rgo3** [comment]
@mesosphere-ci run linux darwin integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run linux integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run darwin integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run mac integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run mac integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run linux integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run mac integration tests

**Pull request merged**
