### PR TITLE
Updated task attach/exec exit strategy.

### PR DESCRIPTION
**Pull request by klueska**

### CODE REVIEW

**Review by armandgrillet — APPROVED** [review]

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run mac integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@bamarni Can you investigate the CI issue? `tests/integrations/test_package.py::test_package`.
```
CMD: ['dcos', 'package', 'repo', 'add', 'helloworld-universe', 'http://helloworld-universe.marathon.mesos:8086/repo']
STDOUT: 
STDERR: Could not access data at URI for repository [helloworld-universe]: http://helloworld-universe.marathon.mesos:8086/repo
```

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by br-lewis** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run linux integration tests

**Comment by klueska** [comment]
This sin't going to work until the 1.13-patch.x branch is working.
i.e. this needs to be fixed / merged first: https://github.com/dcos/dcos-core-cli/pull/85

**Comment by bamarni** [comment]
> @bamarni Can you investigate the CI issue? `tests/integrations/test_package.py::test_package`.
> 
> ```
> CMD: ['dcos', 'package', 'repo', 'add', 'helloworld-universe', 'http://helloworld-universe.marathon.mesos:8086/repo']
> STDOUT: 
> STDERR: Could not access data at URI for repository [helloworld-universe]: http://helloworld-universe.marathon.mesos:8086/repo
> ```

Somewhere in the tests folder there is a reference to the universe server image tag to use during package integration tests. It needs to be bumped to `20181101T202551Z-pull-2038-bc8bc1b86b` in `python/lib/dcoscli/tests/data/helloworld-universe.json`, which is the one with DC/OS 1.13 support.

**Comment by klueska** [comment]
Added to: https://github.com/dcos/dcos-core-cli/pull/85

**Comment by klueska** [comment]
@mesosphere-ci run all integration tests

**Comment by armandgrillet** [comment]
@mesosphere-ci run all integration tests

**Pull request merged**
